import socket
s = socket.socket()
host = socket.gethostname()
port = 8080
print("Hostname for client = " + host)
s.bind((host, port))
s.listen(1)
conn, addr = s.accept()
print("Waiting for incoming connections")
print('Connection Established with', addr)
filename = input(str("Please enter the filename: "))
file = open(filename, 'rb')
file_data = file.read(1024)
conn.send(file_data)
print("Data has been transmitted successfully")